name: lighthouse
# cf. https://github.com/re-taro/re-taro.dev/blob/main/.github/workflows/lighthouse.yml

on:
  pull_request:

env:
  node-version: 18
  pnpm-version: latest

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          node-version: ${{ env.node-version }}

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/.next/cache
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        with:
          version: ${{ env.pnpm-version }}
          run_install: |
            - recursive: true

      - name: production build
        run: pnpm run build

      - name: install Lighthouse cli
        run: |
          pnpm add @lhci/cli@0.8.x

      - name: run Lighthouse cli
        id: lhci
        run: |
          mkdir dist
          touch dist/autorun.txt
          pnpm lhci autorun | grep 'storage.googleapis.com' > ./dist/autorun.txt
          report_url=$(cat ./dist/autorun.txt)
          echo $report_url
          echo "::set-output name=report_url::$report_url"
        continue-on-error: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: json to markdown
        uses: shoma3571/lhci-format-action@v1.3
        id: parse
        with:
          json-file-path: .lighthouseci/assertion-results.json
          report-url: ${{ steps.lhci.outputs.report_url }}

      - name: post comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./result-markdown.md "${URL}"
